#!/bin/bash
# One-command installer for Salesforce Printer Server
# Authentication: OAuth Client Credentials Flow (Consumer Key + Secret only)

set -e

BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "=========================================="
echo "  Salesforce Printer Server Installer"
echo "=========================================="
echo -e "${NC}"

# ── Docker check ────────────────────────────────────────────────────────────

if ! command -v docker &> /dev/null; then
    echo -e "${RED}❌ Docker not found. Installing Docker...${NC}"
    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo sh get-docker.sh
    sudo usermod -aG docker $USER
    echo -e "${GREEN}✓ Docker installed. Please log out and back in, then run this script again.${NC}"
    exit 0
fi

if ! docker ps &> /dev/null; then
    echo -e "${YELLOW}⚠️  Adding user to docker group...${NC}"
    sudo usermod -aG docker $USER
    echo -e "${GREEN}✓ Added to docker group. Activating...${NC}"
    newgrp docker << EONG
        bash $0 "$@"
EONG
    exit 0
fi

if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null 2>&1; then
    echo -e "${YELLOW}⚠️  Installing docker-compose...${NC}"
    sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" \
        -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
    echo -e "${GREEN}✓ docker-compose installed${NC}"
fi

if command -v docker-compose &> /dev/null; then
    DOCKER_COMPOSE="docker-compose"
elif docker compose version &> /dev/null 2>&1; then
    DOCKER_COMPOSE="docker compose"
else
    echo -e "${RED}❌ Failed to install docker-compose${NC}"
    exit 1
fi

mkdir -p config

# ── Step 1: Connected App instructions ──────────────────────────────────────

echo ""
echo -e "${BLUE}=========================================="
echo "  Step 1 of 3 — Salesforce Connected App"
echo "==========================================${NC}"
echo ""
echo "If you haven't already, create a Connected App in Salesforce:"
echo ""
echo "  1. Go to:  Setup → App Manager → New Connected App"
echo ""
echo "  2. Basic Info:"
echo "       • Connected App Name: Printer Server"
echo "       • API Name:           Printer_Server"
echo "       • Contact Email:      (your email)"
echo ""
echo "  3. Enable OAuth Settings:"
echo "       ✓ Enable OAuth Settings"
echo "       • Callback URL: https://localhost:8888/oauth/callback"
echo "         (the value doesn't matter for client credentials)"
echo "       • Selected OAuth Scopes:"
echo "           – Full access (full)"
echo "           – Access the identity URL service (api)"
echo ""
echo "  4. Flow Enablement (scroll down):"
echo "       ✓ Enable Authorization Code and Credentials Flow"
echo "       ✓ Enable Client Credentials Flow"
echo ""
echo "  5. OAuth Policies:"
echo "       ✓ Require Secret for Web Server Flow"
echo "       ✓ Require Proof Key for Code Exchange (PKCE)"
echo ""
echo "  6. Click Save — wait 2–10 minutes for changes to propagate."
echo ""
echo "  7. After saving, go back to the Connected App:"
echo "       Setup → App Manager → (find Printer Server) → View"
echo "       Click 'Manage Consumer Details'"
echo "       Copy your Consumer Key and Consumer Secret."
echo ""
echo -e "${YELLOW}  ⚠️  No certificate upload required."
echo "  ⚠️  No username or password needed.${NC}"
echo ""
read -p "Press ENTER when your Connected App is ready and you have the Consumer Key + Secret..."

# ── Step 2: Credentials ──────────────────────────────────────────────────────

echo ""
echo -e "${BLUE}=========================================="
echo "  Step 2 of 3 — Enter Credentials"
echo "==========================================${NC}"
echo ""

echo "  Client Credentials Flow requires your org's My Domain URL."
echo "  Find it in Salesforce: Setup → My Domain"
echo "  Example: https://mycompany.my.salesforce.com"
echo ""
read -p "  Instance URL: " INSTANCE_URL
# Strip trailing slash
INSTANCE_URL="${INSTANCE_URL%/}"

echo ""
read -p "  Consumer Key (Client ID): " CLIENT_ID
read -sp "  Consumer Secret:          " CLIENT_SECRET
echo ""

# ── Step 3: Write config & build ─────────────────────────────────────────────

echo ""
echo -e "${BLUE}=========================================="
echo "  Step 3 of 3 — Save & Start"
echo "==========================================${NC}"
echo ""

cat > config/config.toml << EOF
# Salesforce Printer Server Configuration
# Generated by install.sh

[salesforce]
instance_url = "${INSTANCE_URL}"

[auth]
method        = "client_credentials"
client_id     = "${CLIENT_ID}"
client_secret = "${CLIENT_SECRET}"

[logging]
level = "INFO"
EOF

chmod 600 config/config.toml
echo -e "${GREEN}  ✓ Configuration saved to config/config.toml${NC}"

echo ""
echo -e "${BLUE}  🐋 Building Docker image (this takes a minute)...${NC}"
$DOCKER_COMPOSE build --no-cache

echo ""
echo -e "${BLUE}  🚀 Starting service...${NC}"
$DOCKER_COMPOSE up -d --force-recreate

sleep 2

# ── Install host-side sf-printer wrapper ────────────────────────────────────

echo ""
echo -e "${BLUE}  🔧 Installing sf-printer command to /usr/local/bin/sf-printer...${NC}"

INSTALL_DIR="$(pwd)"

sudo tee /usr/local/bin/sf-printer > /dev/null << EOF
#!/bin/bash
# sf-printer — Salesforce Printer Server host wrapper
# Auto-generated by install.sh

CONTAINER="sf-printer-server"
INSTALL_DIR="${INSTALL_DIR}"

if command -v docker-compose &> /dev/null; then
    DC="docker-compose -f \${INSTALL_DIR}/docker-compose.yml"
elif docker compose version &> /dev/null 2>&1; then
    DC="docker compose -f \${INSTALL_DIR}/docker-compose.yml"
else
    echo "❌ docker compose not found"
    exit 1
fi

case "\$1" in
    logs)
        docker logs -f "\$CONTAINER"
        ;;
    stop)
        echo "Stopping \$CONTAINER..."
        \$DC down
        ;;
    restart)
        echo "Restarting \$CONTAINER..."
        \$DC restart
        ;;
    status)
        docker ps --filter "name=\$CONTAINER" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
        ;;
    config)
        shift
        if [ \$# -eq 0 ]; then
            docker exec "\$CONTAINER" sf-printer config
        else
            docker exec -it "\$CONTAINER" sf-printer config "\$@"
        fi
        ;;
    verify)
        docker exec -it "\$CONTAINER" sf-printer verify
        ;;
    *)
        echo ""
        echo "Salesforce Printer Server"
        echo ""
        echo "Usage: sf-printer <command>"
        echo ""
        echo "Commands:"
        echo "  logs                        Follow server logs (Ctrl+C to exit)"
        echo "  stop                        Stop the server"
        echo "  restart                     Restart the server"
        echo "  status                      Show container status"
        echo "  config                      Show current configuration"
        echo "  config --client-id          Set Consumer Key  (prompts if no value given)"
        echo "  config --client-secret      Set Consumer Secret  (prompts securely)"
        echo "  config --instance-url URL   Set Salesforce instance URL"
        echo "  verify                      Test Salesforce connection"
        echo ""
        ;;
esac
EOF

sudo chmod +x /usr/local/bin/sf-printer
echo -e "${GREEN}  ✓ sf-printer command installed${NC}"

# ── Done ────────────────────────────────────────────────────────────────────

if docker ps | grep -q sf-printer-server; then
    echo ""
    echo -e "${GREEN}=========================================="
    echo "  ✅ Installation Complete!"
    echo "==========================================${NC}"
    echo ""
    echo "  Service is running!"
    echo ""
    echo "  Commands:"
    echo "    sf-printer logs                 Follow server logs"
    echo "    sf-printer stop                 Stop the server"
    echo "    sf-printer restart              Restart the server"
    echo "    sf-printer status               Show container status"
    echo "    sf-printer config               Show current config"
    echo "    sf-printer config --client-id   Update Consumer Key (prompts)"
    echo "    sf-printer config --client-secret   Update Consumer Secret (prompts)"
    echo "    sf-printer verify               Test Salesforce connection"
    echo ""
else
    echo ""
    echo -e "${YELLOW}  ⚠️  Service may not have started correctly.${NC}"
    echo "  Check logs:  sf-printer logs"
fi
